# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: efbcc3061e0cdb728427987c70d66cce060aab9126c98578fca21754ff4f521768554b2b2a35278b15430e0fe139fda423bc714a9caeb49bcf9ece734645cfa2

test:
  secret_key_base: 5379de0a8824593588b43e26e84674831e9d78222ef32980874df4cfd366816058b684b1c340900748ec507994f652bae32cc54fda6fd80c53e98cf6de8efac1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
